In [170]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [186]:
data = pd.read_csv('processed_data.csv')

In [187]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 35 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          10915 non-null  int64
 1   Business Name       10915 non-null  object
 2   Average Rating      10915 non-null  float64
 3   Review Grade        10915 non-null  object
 4   Title               10915 non-null  object
 5   Review              10915 non-null  object
 6   Rating              10915 non-null  int64
 7   Time                10915 non-null  object
 8   Review Count        10915 non-null  object
 9   Country             10915 non-null  object
 10  Status              5947 non-null   object
 11  Month               10915 non-null  object
 12  Month Numbers       10915 non-null  int64
 13  Years               10915 non-null  object
 14  Rating Distance     10915 non-null  float64
 15  body_neg            10915 non-null  float64
 16  body_neu            10915 non-null  float64
 17  body_pos            10915 non-null  float64
 18  body_com            10915 non-null  float64
 19  title_neg           10915 non-null  float64
 20  title_neu           10915 non-null  float64
 21  title_pos           10915 non-null  float64
 22  title_com           10915 non-null  float64
 23  Title Length        10915 non-null  int64
 24  Body Length         10915 non-null  int64
 25  Total Length        10915 non-null  int64
 26  Title Emoji         10915 non-null  int64
 27  Body Emoji          10915 non-null  int64
 28  Title Ellipses      10915 non-null  int64
 29  Body Ellipses       10915 non-null  int64
 30  Title Hashtags      10915 non-null  int64
 31  Body Hashtags       10915 non-null  int64
 32  Title Exclamations  10915 non-null  int64
 33  Body Exclamations   10915 non-null  int64
 34  Status Rank         10915 non-null  int64
dtypes: float64(10), int64(15), object(10)
memory usage: 2.9+ MB

In [188]:
data.drop(data.columns[[0,1,2,3,4,10]], axis = 1, inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 29 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Review              10915 non-null  object
 1   Rating              10915 non-null  int64
 2   Time                10915 non-null  object
 3   Review Count        10915 non-null  object
 4   Country             10915 non-null  object
 5   Month               10915 non-null  object
 6   Month Numbers       10915 non-null  int64
 7   Years               10915 non-null  object
 8   Rating Distance     10915 non-null  float64
 9   body_neg            10915 non-null  float64
 10  body_neu            10915 non-null  float64
 11  body_pos            10915 non-null  float64
 12  body_com            10915 non-null  float64
 13  title_neg           10915 non-null  float64
 14  title_neu           10915 non-null  float64
 15  title_pos           10915 non-null  float64
 16  title_com           10915 non-null  float64
 17  Title Length        10915 non-null  int64
 18  Body Length         10915 non-null  int64
 19  Total Length        10915 non-null  int64
 20  Title Emoji         10915 non-null  int64
 21  Body Emoji          10915 non-null  int64
 22  Title Ellipses      10915 non-null  int64
 23  Body Ellipses       10915 non-null  int64
 24  Title Hashtags      10915 non-null  int64
 25  Body Hashtags       10915 non-null  int64
 26  Title Exclamations  10915 non-null  int64
 27  Body Exclamations   10915 non-null  int64
 28  Status Rank         10915 non-null  int64
dtypes: float64(9), int64(14), object(6)
memory usage: 2.4+ MB

In [190]:
data.drop(data.columns[[0,2,5,6,7,8]], axis = 1, inplace = True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              10915 non-null  int64
 1   Review Count        10915 non-null  object
 2   Country             10915 non-null  object
 3   body_neg            10915 non-null  float64
 4   body_neu            10915 non-null  float64
 5   body_pos            10915 non-null  float64
 6   body_com            10915 non-null  float64
 7   title_neg           10915 non-null  float64
 8   title_neu           10915 non-null  float64
 9   title_pos           10915 non-null  float64
 10  title_com           10915 non-null  float64
 11  Title Length        10915 non-null  int64
 12  Body Length         10915 non-null  int64
 13  Total Length        10915 non-null  int64
 14  Title Emoji         10915 non-null  int64
 15  Body Emoji          10915 non-null  int64
 16  Title Ellipses      10915 non-null  int64
 17  Body Ellipses       10915 non-null  int64
 18  Title Hashtags      10915 non-null  int64
 19  Body Hashtags       10915 non-null  int64
 20  Title Exclamations  10915 non-null  int64
 21  Body Exclamations   10915 non-null  int64
 22  Status Rank         10915 non-null  int64
dtypes: float64(8), int64(13), object(2)
memory usage: 1.9+ MB

In [205]:
data.info()

ph_data = data[data['Country'] == 'PH']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10915 entries, 0 to 10914
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              10915 non-null  int64
 1   Review Count        10915 non-null  object
 2   Country             10915 non-null  object
 3   body_neg            10915 non-null  float64
 4   body_neu            10915 non-null  float64
 5   body_pos            10915 non-null  float64
 6   body_com            10915 non-null  float64
 7   title_neg           10915 non-null  float64
 8   title_neu           10915 non-null  float64
 9   title_pos           10915 non-null  float64
 10  title_com           10915 non-null  float64
 11  Title Length        10915 non-null  int64
 12  Body Length         10915 non-null  int64
 13  Total Length        10915 non-null  int64
 14  Title Emoji         10915 non-null  int64
 15  Body Emoji          10915 non-null  int64
 16  Title Ellipses      10915 non-null  int64
 17  Body Ellipses       10915 non-null  int64
 18  Title Hashtags      10915 non-null  int64
 19  Body Hashtags       10915 non-null  int64
 20  Title Exclamations  10915 non-null  int64
 21  Body Exclamations   10915 non-null  int64
 22  Status Rank         10915 non-null  int64
dtypes: float64(8), int64(13), object(2)
memory usage: 1.9+ MB

In [206]:
ph_data.drop(['Country'], axis = 1, inplace = True)
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6105 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              6105 non-null   int64
 1   Review Count        6105 non-null   object
 2   body_neg            6105 non-null   float64
 3   body_neu            6105 non-null   float64
 4   body_pos            6105 non-null   float64
 5   body_com            6105 non-null   float64
 6   title_neg           6105 non-null   float64
 7   title_neu           6105 non-null   float64
 8   title_pos           6105 non-null   float64
 9   title_com           6105 non-null   float64
 10  Title Length        6105 non-null   int64
 11  Body Length         6105 non-null   int64
 12  Total Length        6105 non-null   int64
 13  Title Emoji         6105 non-null   int64
 14  Body Emoji          6105 non-null   int64
 15  Title Ellipses      6105 non-null   int64
 16  Body Ellipses       6105 non-null   int64
 17  Title Hashtags      6105 non-null   int64
 18  Body Hashtags       6105 non-null   int64
 19  Title Exclamations  6105 non-null   int64
 20  Body Exclamations   6105 non-null   int64
 21  Status Rank         6105 non-null   int64
dtypes: float64(8), int64(13), object(1)
memory usage: 1.1+ MB

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [207]:
ph_data['Review Count'].value_counts()
ph_data.head(10)

,Rating,Review Count,body_neg,body_neu,body_pos,body_com,title_neg,title_neu,title_pos,title_com,...,Total Length,Title Emoji,Body Emoji,Title Ellipses,Body Ellipses,Title Hashtags,Body Hashtags,Title Exclamations,Body Exclamations,Status Rank
1,4,1,0.000,1.000,0.000,0.0000,0.000,1.000,0.0,0.0000,...,31,0,0,0,0,0,0,0,0,1
2,5,1,0.000,0.854,0.146,0.4404,0.000,1.000,0.0,0.0000,...,36,0,0,0,0,1,5,0,0,0
3,5,1,0.000,1.000,0.000,0.0000,0.000,1.000,0.0,0.0000,...,32,0,0,0,0,1,5,0,0,0
4,5,1,0.183,0.817,0.000,-0.4005,0.000,1.000,0.0,0.0000,...,30,0,1,0,0,1,4,0,0,0
5,5,1,0.000,0.633,0.367,0.4404,0.000,1.000,0.0,0.0000,...,11,0,1,0,0,1,1,0,0,0
7,4,1,0.062,0.795,0.143,0.9690,0.000,1.000,0.0,0.0000,...,251,0,0,0,0,1,1,0,2,0
8,1,1,0.237,0.738,0.024,-0.9765,0.000,1.000,0.0,0.0000,...,122,0,0,0,1,1,3,0,3,1
9,1,1,0.237,0.738,0.024,-0.9765,0.000,1.000,0.0,0.0000,...,122,0,0,0,1,1,3,0,3,1
10,1,[Beer],0.237,0.738,0.024,-0.9765,0.000,1.000,0.0,0.0000,...,122,0,0,0,1,1,3,0,3,1
14,1,1,0.141,0.859,0.000,-0.8885,0.761,0.239,0.0,-0.4898,...,102,0,0,0,0,0,0,3,0,0

In [208]:
ph_data.drop(10, axis = 0, inplace = True)

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [209]:
ph_data.head(10)

,Rating,Review Count,body_neg,body_neu,body_pos,body_com,title_neg,title_neu,title_pos,title_com,...,Total Length,Title Emoji,Body Emoji,Title Ellipses,Body Ellipses,Title Hashtags,Body Hashtags,Title Exclamations,Body Exclamations,Status Rank
1,4,1,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000,...,31,0,0,0,0,0,0,0,0,1
2,5,1,0.000,0.854,0.146,0.4404,0.000,1.000,0.000,0.0000,...,36,0,0,0,0,1,5,0,0,0
3,5,1,0.000,1.000,0.000,0.0000,0.000,1.000,0.000,0.0000,...,32,0,0,0,0,1,5,0,0,0
4,5,1,0.183,0.817,0.000,-0.4005,0.000,1.000,0.000,0.0000,...,30,0,1,0,0,1,4,0,0,0
5,5,1,0.000,0.633,0.367,0.4404,0.000,1.000,0.000,0.0000,...,11,0,1,0,0,1,1,0,0,0
7,4,1,0.062,0.795,0.143,0.9690,0.000,1.000,0.000,0.0000,...,251,0,0,0,0,1,1,0,2,0
8,1,1,0.237,0.738,0.024,-0.9765,0.000,1.000,0.000,0.0000,...,122,0,0,0,1,1,3,0,3,1
9,1,1,0.237,0.738,0.024,-0.9765,0.000,1.000,0.000,0.0000,...,122,0,0,0,1,1,3,0,3,1
14,1,1,0.141,0.859,0.000,-0.8885,0.761,0.239,0.000,-0.4898,...,102,0,0,0,0,0,0,3,0,0
15,1,1,0.182,0.818,0.000,-0.7774,0.000,0.507,0.493,0.4427,...,49,0,0,0,0,0,0,3,0,1

In [210]:
review_count = []

for row in ph_data['Review Count']:
    review_count.append(int(row))
    
ph_data['# Reviews'] = review_count
ph_data['Target Rating'] = ph_data['Rating']

<ipython-input-210-6d28182b2500>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ph_data['# Reviews'] = review_count
<ipython-input-210-6d28182b2500>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ph_data['Target Rating'] = ph_data['Rating']

In [211]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rating              6104 non-null   int64
 1   Review Count        6104 non-null   object
 2   body_neg            6104 non-null   float64
 3   body_neu            6104 non-null   float64
 4   body_pos            6104 non-null   float64
 5   body_com            6104 non-null   float64
 6   title_neg           6104 non-null   float64
 7   title_neu           6104 non-null   float64
 8   title_pos           6104 non-null   float64
 9   title_com           6104 non-null   float64
 10  Title Length        6104 non-null   int64
 11  Body Length         6104 non-null   int64
 12  Total Length        6104 non-null   int64
 13  Title Emoji         6104 non-null   int64
 14  Body Emoji          6104 non-null   int64
 15  Title Ellipses      6104 non-null   int64
 16  Body Ellipses       6104 non-null   int64
 17  Title Hashtags      6104 non-null   int64
 18  Body Hashtags       6104 non-null   int64
 19  Title Exclamations  6104 non-null   int64
 20  Body Exclamations   6104 non-null   int64
 21  Status Rank         6104 non-null   int64
 22  # Reviews           6104 non-null   int64
 23  Target Rating       6104 non-null   int64
dtypes: float64(8), int64(15), object(1)
memory usage: 1.2+ MB

In [212]:
ph_data.drop(['Review Count'], axis = 1, inplace = True)
ph_data.drop(['Rating'], axis = 1, inplace = True)

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [ ]:
ph_data.iloc[:, 0:-1]

In [213]:
ph_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6104 entries, 1 to 10914
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   body_neg            6104 non-null   float64
 1   body_neu            6104 non-null   float64
 2   body_pos            6104 non-null   float64
 3   body_com            6104 non-null   float64
 4   title_neg           6104 non-null   float64
 5   title_neu           6104 non-null   float64
 6   title_pos           6104 non-null   float64
 7   title_com           6104 non-null   float64
 8   Title Length        6104 non-null   int64
 9   Body Length         6104 non-null   int64
 10  Total Length        6104 non-null   int64
 11  Title Emoji         6104 non-null   int64
 12  Body Emoji          6104 non-null   int64
 13  Title Ellipses      6104 non-null   int64
 14  Body Ellipses       6104 non-null   int64
 15  Title Hashtags      6104 non-null   int64
 16  Body Hashtags       6104 non-null   int64
 17  Title Exclamations  6104 non-null   int64
 18  Body Exclamations   6104 non-null   int64
 19  Status Rank         6104 non-null   int64
 20  # Reviews           6104 non-null   int64
 21  Target Rating       6104 non-null   int64
dtypes: float64(8), int64(14)
memory usage: 1.1 MB

In [214]:
X = ph_data.iloc[:, 0:-1].values
y = ph_data.iloc[:, -1].values

ph_data.head(5)

,body_neg,body_neu,body_pos,body_com,title_neg,title_neu,title_pos,title_com,Title Length,Body Length,...,Body Emoji,Title Ellipses,Body Ellipses,Title Hashtags,Body Hashtags,Title Exclamations,Body Exclamations,Status Rank,# Reviews,Target Rating
1,0.000,1.000,0.000,0.0000,0.0,1.0,0.0,0.0,9,22,...,0,0,0,0,0,0,0,1,1,4
2,0.000,0.854,0.146,0.4404,0.0,1.0,0.0,0.0,8,28,...,0,0,0,1,5,0,0,0,1,5
3,0.000,1.000,0.000,0.0000,0.0,1.0,0.0,0.0,8,24,...,0,0,0,1,5,0,0,0,1,5
4,0.183,0.817,0.000,-0.4005,0.0,1.0,0.0,0.0,8,22,...,1,0,0,1,4,0,0,0,1,5
5,0.000,0.633,0.367,0.4404,0.0,1.0,0.0,0.0,3,8,...,1,0,0,1,1,0,0,0,1,5

In [225]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [226]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [278]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[400   0   0   0  47]
 [ 17   0   0   0   1]
 [ 16   0   0   0  18]
 [  8   0   0   1  52]
 [ 33   0   2   3 623]]
Accuracy: 83.86568386568388%
Precision Score: 0.7765804512973067
Recall Score: 0.8386568386568387
F1 Score: 0.8006562844435219
Mean Squared Error: 1.2915642915642915
Root Mean Squared Error: 1.136470101482785
Mean Absolute Error: 0.4021294021294021

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [277]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[399   0   1   2  45]
 [ 15   0   1   0   2]
 [ 17   0   0   3  14]
 [ 10   0   2   5  44]
 [ 33   1   4  16 607]]
Accuracy: 82.80098280098281%
Precision Score: 0.7792989259174723
Recall Score: 0.828009828009828
F1 Score: 0.8016113418732682
Mean Squared Error: 1.316953316953317
Root Mean Squared Error: 1.1475858647409862
Mean Absolute Error: 0.4176904176904177

In [276]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[401   0   0   0  46]
 [ 17   0   0   0   1]
 [ 16   0   0   0  18]
 [  9   0   0   0  52]
 [ 38   0   0   0 623]]
Accuracy: 83.86568386568388%
Precision Score: 0.7609708650249191
Recall Score: 0.8386568386568387
F1 Score: 0.7978528111761147
Mean Squared Error: 1.3423423423423424
Root Mean Squared Error: 1.1585949863271212
Mean Absolute Error: 0.411957411957412

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [275]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[405   0   0   0  42]
 [ 16   0   0   0   2]
 [ 18   0   0   0  16]
 [  7   0   0   0  54]
 [ 36   0   0   0 625]]
Accuracy: 84.35708435708436%
Precision Score: 0.7654576270486523
Recall Score: 0.8435708435708436
F1 Score: 0.802555470208861
Mean Squared Error: 1.2571662571662572
Root Mean Squared Error: 1.121234256150898
Mean Absolute Error: 0.3906633906633907

/Users/cheselle/opt/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [274]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[ 49 254 140   2   2]
 [  1  10   7   0   0]
 [  0   9  21   3   1]
 [  0   3  49   7   2]
 [  3  41 400 154  63]]
Accuracy: 12.285012285012286%
Precision Score: 0.8435368833620531
Recall Score: 0.12285012285012285
F1 Score: 0.1710804286408356
Mean Squared Error: 2.556920556920557
Root Mean Squared Error: 1.599037384466216
Mean Absolute Error: 1.4054054054054055

In [273]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[391   8   4  10  34]
 [ 11   2   3   0   2]
 [  9   1   3   4  17]
 [  8   0   2  19  32]
 [ 42   0  13  44 562]]
Accuracy: 80.01638001638001%
Precision Score: 0.7990919170019043
Recall Score: 0.8001638001638002
F1 Score: 0.799118872520273
Mean Squared Error: 1.3701883701883701
Root Mean Squared Error: 1.1705504560626039
Mean Absolute Error: 0.45454545454545453

In [271]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import confusion_matrix, accuracy_score, mean_squared_error, mean_absolute_error, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: {}%".format(accuracy_score(y_test, y_pred) *100 ))
print("Precision Score: {}".format(precision_score(y_test, y_pred, average = 'weighted')))
print("Recall Score: {}".format(recall_score(y_test, y_pred, average = 'weighted')))
print("F1 Score: {}".format(f1_score(y_test, y_pred, average = 'weighted') ))
print("Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred) ))
print("Root Mean Squared Error: {}".format(mean_squared_error(y_test, y_pred, squared = False)))
print("Mean Absolute Error: {}".format(mean_absolute_error(y_test, y_pred) ))

[[411   1   1   0  34]
 [ 13   2   0   1   2]
 [ 15   1   3   1  14]
 [  9   0   0   6  46]
 [ 45   0   3   7 606]]
Accuracy: 84.19328419328419%
Precision Score: 0.8118176755093591
Recall Score: 0.8419328419328419
F1 Score: 0.8161656373428028
Mean Squared Error: 1.2841932841932842
Root Mean Squared Error: 1.1332225219228942
Mean Absolute Error: 0.39803439803439805